title: Hey, hi, Thodoris here :-)
escription: > # this means to ignore newlines until "baseurl:"
  Born as G(r)eek.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Thodoris Bais
author-img: thodoris-bais.jpg
about-author: JUG Leader. Java Jury @ EDITx. Inspired local communities to take the next step. Born as G(r)eek. Growing up in the ðŸ‡³ðŸ‡±. Speaks three languages on a daily basis. Prefers his own quotes. Never fails, always learns. Enjoys good food, not coffee. Goalkeeper.
twitter: ThodorisBais
facebook: toubou.techblog
github: toubou91
linkedin: thodorisbais
tumblr: thodoris.bais@gmail.com

# Disqus
discus-identifier: thodorisbais # add your discus identifier

# Tracker
analytics: UA-108110726-1

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
